version: "3.8"

services:
  kafka-1:
    image: apache/kafka:4.0.0
    container_name: kafka-1
    ports:
      - "9091:9091"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CLUSTER_ID: "cXh3q8BmQPe2wkqvQJK8Wg"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9094,2@kafka-2:9094,3@kafka-3:9094"
      KAFKA_LISTENERS: "INTERNAL://kafka-1:9192,CONTROLLER://:9094,EXTERNAL://:9091"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-1:9192,EXTERNAL://localhost:9091"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

  kafka-2:
    image: apache/kafka:4.0.0
    container_name: kafka-2
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CLUSTER_ID: "cXh3q8BmQPe2wkqvQJK8Wg"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9094,2@kafka-2:9094,3@kafka-3:9094"
      KAFKA_LISTENERS: "INTERNAL://kafka-2:9192,CONTROLLER://:9094,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-2:9192,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

  kafka-3:
    image: apache/kafka:4.0.0
    container_name: kafka-3
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CLUSTER_ID: "cXh3q8BmQPe2wkqvQJK8Wg"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9094,2@kafka-2:9094,3@kafka-3:9094"
      KAFKA_LISTENERS: "INTERNAL://kafka-3:9192,CONTROLLER://:9094,EXTERNAL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-3:9192,EXTERNAL://localhost:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
